# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ""
name: WinchPass
email: contact@winchpass.com
description: >- 
  WinchPass is a Chrome extension intended for users of iCloud Keychain that have a Windows PC.  
  It fills out passwords automatically and doesn't keep any data.  
  It uses one-time pad encryption and QR codes to link your phone to Chrome.  
  Once the password is filled, the encryption key is discarded and cannot be reused.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://winchpass.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

webmaster_verifications:
  google: QYyCOxTA3Q9xlEAG75ixBje4119AzYHWjrzl4__uNis
  # bing: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234

include:
  - _headers
  - _redirects

exclude:
  - "*.sh"
  - Gemfile
  - Gemfile.lock
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
